### ISSUE TITLE
Project still alive ?

### ISSUE THREAD

**Issue by realgooseman** [SyedAounHaiderNaqvi/To-Do_App#13]
Hi @SyedAounHaiderNaqvi,

This app is the only direct alternative to "Microsoft To-Do" I think, but local and more private. Great potential.
I came across it not so long ago, and I was wondering if you're still maintaining it or not ?

If so, I would like to suggest new features / improvements

**Visibility :** Publishing the app on [AlternativeTo](https://alternativeto.net/) to gain visibility and attract new users
**Localization :** Setting up Crowdin page to translate the app with contributions, will help gain visibility too
**New features :** Recurring tasks (daily, weekly, monthly, specific date), resizable window mini-mode, pin on top

**Comment by SyedAounHaiderNaqvi** [comment]
Hey! I apologize for such a late reply. I was honestly busy with life's other endeavors and unfortunately could not provide any resource to this app, but the good news is that you can expect more updates now!!

**Comment by realgooseman** [comment]
Of course, nice to hear it's not abandoned.
I look forward to see this app being improved (with the features I mentioned if possible as well)
