### ISSUE TITLE
Sidebar tint

### ISSUE THREAD

**Issue by itsWindows11** [SyedAounHaiderNaqvi/To-Do_App#5]
The sidebar is missing tint, in the same example image as #4:

![unknown.png](https://user-images.githubusercontent.com/81253203/185408335-bba44df2-dca0-4cbd-aadd-948d7e9513ad.png)

**Comment by SyedAounHaiderNaqvi** [comment]
Updated the code and now this will work
![image](https://github.com/SyedAounHaiderNaqvi/To-Do_App/assets/88966722/eb87d64e-f0e2-431e-af3f-7248d8965a86)
